#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Stop the process and return false
ctrl_c() {
  echo "Stoping checks..."
  false
}

# ctrl_c is the name of the signal ctrl_c function for SIGINT signal
trap "ctrl_c" SIGINT

echo
echo "Pre-commit checks started..."

# Check tsconfig standards
npm run typescript:check && echo -e "\ntype check successful." || (
  echo "Failed Type check !!!"
  echo "Make the changes required above."
  false
)
echo

# Code format using prettier
npm run lint-staged && echo -e "\nCode format successful, and added to staging." || (
  echo "Code format failed !!!"
  echo "Check the error and fix the warning(s) or error(s)."
  false
)
echo

# Build check
npm run build && echo -e "\nBuild successful." || (
  echo "Build failed !!!"
  echo "Next build failed: View the errors above to see why."
  false
)
echo

echo "All checks completed."
exit 0

# Wait till all the steps and checks completes.
sleep 300 # 5mins
exit 0